---
title: "Równania Różniczkowe 1A"

toc: true
toc-depth: 3
toc-expand: true

format:
  html:
    page-layout: article
---

::: {.course-info-card}
::: {.course-info-grid}
::: {.course-info-item}
::: {.label}
Instytucja
:::
::: {.value}
Uniwersytet Wrocławski
:::
:::

::: {.course-info-item}
::: {.label}
Semestr
:::
::: {.value}
Letni 2016/17
:::
:::

::: {.course-info-item}
::: {.label}
Wykładowca
:::
::: {.value}
dr hab. Robert Stańczy
:::
:::
:::
:::

Prowadzę jedną z grup ćwiczeniowych do wykładu Roberta Stańczego.

## Materiały do nauki

* [Skrypt Raczyńskiego](../../assets/pdf/RR 1A - Raczyński.pdf) - Podstawowy skrypt do kursu.
* [Skrypt Palczewskiego](../../assets/pdf/RRZ skrypt - Palczewski.pdf) - Obszerny skrypt do równań różniczkowych zwyczajnych.
* [Zadania Palczewskiego](../../assets/pdf/RRZ zadania - Palczewski.pdf) - Zbiór zadań z rozwiązaniami i wskazówkami.


### Równania różniczkowe cząstkowe

* [Metoda charakterystyk](../../assets/pdf/charakterystyki.pdf) - Rozwiązane zadania na metodę charakterystyk.
* [Równania drugiego rzędu](http://www.math.uni.lodz.pl/~karpinw/zadania/RRCz1/II_rzad_zadania.PDF) - Rozwiązane zadania z równań drugiego rzędu (W. Karpiński).
* [Metoda rozdzielania zmiennych](../../assets/pdf/rozdzielaniezmiennych.pdf) - Rozwiązane zadania na metodę rozdzielania zmiennych.


## Listy zadań

* [Lista 1](../../assets/pdf/RR01.pdf)
* [Lista 2](../../assets/pdf/RR02.pdf)
* [Lista 3](../../assets/pdf/RR03.pdf)
* [Lista 4](../../assets/pdf/RR04.pdf)
* [Lista 5](../../assets/pdf/RR05.pdf)
* [Lista 6](../../assets/pdf/RR06.pdf)
* [Lista 7](../../assets/pdf/RR07.pdf)
* [Lista 8](../../assets/pdf/RR08.pdf)
* [Lista 9](../../assets/pdf/RR09.pdf)
* [Lista 10](../../assets/pdf/RR10.pdf)
* [Lista 11](../../assets/pdf/RR11.pdf)
* [Lista 12](../../assets/pdf/RR12.pdf)
* [Lista 13](../../assets/pdf/RR13.pdf)
* [Lista 14](../../assets/pdf/RR14.pdf)
* [Lista 15](../../assets/pdf/RR15.pdf) - Lista powtórzeniowa.
