fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-xml
      - id: check-toml
      # - id: no-commit-to-branch
      - id: pretty-format-json
        args: ["--autofix", "--indent=4"]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
