project:
  type: website
  output-dir: docs

website:
  title: "bwrob blog"
  navbar:
    right:
      - pages/about.qmd
      - pages/resume.qmd
      - pages/hobbies.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        text: Github
        href: https://github.com/bwrob/
    logo: assets/python_mug.png
format:
  html:
    theme: darkly
    css: styles.css
