project:
  type: website
  output-dir: docs

website:
  title: "bwrob blog"
  navbar:
    search: true
    collapse: true
    pinned: true
    right:
      - text: "Posts" 
        icon: cpu
        file: index.qmd
      - icon: file-earmark-text
        file: pages/resume.qmd
      - icon: controller
        file: pages/hobbies.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        text: Github
        href: https://github.com/bwrob/
    logo: assets/python_mug.png


format:
  html:
    theme: darkly
    css: styles.css
