project:
  type: website
  output-dir: _site
  resources:
    - "assets/"
    - "css/"

website:
  title: "bwrob blog"
  site-url: "https://bwrob.github.io/"
  repo-url: "https://github.com/bwrob/bwrob.github.io"
  description: "Personal blog about programming, finance, and physics."

  favicon: assets/logo/favicon.png
  twitter-card:
    title: "bwrob blog"
    description: "bwrob personal and professional blog"
    image: assets/logo/logo_full.png
    card-style: summary_large_image

  open-graph:
    title: "bwrob blog"
    description: "bwrob personal and professional blog"
    image: assets/logo/logo_full.png
    site-name: "bwrob blog"

  image: assets/logo/logo_full.png

  page-navigation: true
  back-to-top-navigation: true
  page-footer: "bwrob.github.io · Terminal Theme · 2026. Built with Quarto."

  search:
    location: navbar
    type: overlay

  navbar:
    logo: assets/logo/logo_full.png
    collapse: true
    pinned: true
    right:
      - text: "posts"
        icon: cpu
        file: index.qmd
      - text: "resume"
        icon: file-earmark-text
        file: resume/index.qmd
      - text: "teaching"
        icon: tablet-landscape
        file: teaching/index.qmd
      - text: "hobbies"
        icon: controller
        file: hobbies/index.qmd
      - text: "debug-dojo"
        icon: bug-fill
        href: https://bwrob.github.io/debug-dojo/
      - text: "sus-inspector"
        icon: bug-fill
        href: https://bwrob.github.io/sus-inspector/
      - icon: linkedin
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        href: https://github.com/bwrob/
      - icon: rss
        href: index.xml

comments:
  giscus:
    repo: bwrob/bwrob.github.io
    mapping: pathname
    input-position: top
    loading: lazy
    reactions-enabled: false

format:
  html:
    code-link: true
    smooth-scroll: true
    reading-progress: true
    theme:
      dark: [darkly, css/theme-dark.scss]
      light: [flatly, css/theme-light.scss]
    css: css/styles.css
    # include-after-body:
    #  - js/post-meta.html
    highlight-style: github
    code-fold: show
    code-summary: "Show the code"
    code-copy: true
    code-line-numbers: true
    code-block-border-left: true
    code-annotations: below
    lightbox: true
