project:
  type: website
  output-dir: docs

website:
  title: "bwrob blog"
  site-url: "https://bwrob.github.io"
  description: "bwrob personal and proffesional blog"
  
  favicon: assets/python_mug.png
  twitter-card: true
  open-graph: true
  image: assets/python_mug.png

  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, bwrob"

  navbar:
    search: true
    collapse: true
    pinned: true
    right:
      - text: "Posts" 
        icon: cpu
        file: index.qmd
      - text: "Resume"
        icon: file-earmark-text
        file: pages/resume.qmd
      - text: "Hobbies"
        icon: controller
        file: pages/hobbies.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        href: https://github.com/bwrob/
      - icon: rss
        href: index.xml
    logo: assets/python_mug.png


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
