project:
  type: website
  output-dir: _site

website:
  title: "bwrob blog"
  site-url: "https://bwrob.github.io"
  description: "bwrob personal and professional blog"

  favicon: logo/python_mug.png
  twitter-card:
    title: "bwrob blog"
    description: "bwrob personal and professional blog"
    image: logo/python_mug.png
    card-style: summary_large_image

  open-graph:
    title: "bwrob blog"
    description: "bwrob personal and professional blog"
    image: logo/python_mug.png
    site-name: "bwrob blog"

  image: logo/python_mug.png

  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, bwrob"

  navbar:
    search: true
    collapse: true
    pinned: true
    right:
      - text: "Posts"
        icon: cpu
        file: index.qmd
      - text: "Resume"
        icon: file-earmark-text
        file: pages/resume.qmd
      - text: "Teaching"
        icon: tablet-landscape
        file: pages/teaching.qmd
      - text: "Hobbies"
        icon: controller
        file: pages/hobbies.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        href: https://github.com/bwrob/
      - icon: rss
        href: index.xml
    logo: logo/python_mug.png

format:
  html:
    theme:
      dark: [darkly, theme-dark.scss]
      light: flatly

    css: styles.css
