project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - hobbies.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/bartoszmwroblewski/
      - icon: github
        text: Github
        href: https://github.com/bwrob/

format:
  html:
    theme: darkly
    css: styles.css
