[tool.poetry]
name = "bwrob-github-io"
version = "0.1.0"
description = ""
authors = ["bwrob <bw2002@wp.pl>"]
readme = "README.md"
packages = [{ include = "scripts" }]

[tool.poetry.dependencies]
python = "^3.12"

pandas = "^2.2.2"
pandas-stubs = "^2.2.2.240807"
psutil = "^6.0.0"
scipy = "^1.14.1"

[tool.poetry.group.dev.dependencies]
pre_commit = "^3.3.2"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.docformatter]
recursive = true
in-place = true
black = true
pre-summary-newline = false
blank = true
