[tool.poetry]
name = "bwrob-github-io"
version = "0.1.0"
description = ""
authors = ["bwrob <bw2002@wp.pl>"]
readme = "README.md"
packages = [{include = "bwrob"}]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
numpy = "^1.26.4"
black = "^24.4.2"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
