[tool.poetry]
name = "bwrob-github-io"
version = "0.1.0"
description = ""
authors = ["bwrob <bw2002@wp.pl>"]
readme = "README.md"
packages = [{ include = "scripts" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"

matplotlib = "^3.9.2"
mplfinance = "^0.12.10b0"
pandas = "^2.2.2"
pandas-stubs = "^2.2.2.240807"
plotly = "^5.24.1"
psutil = "^5.9.0"
scipy = "^1.14.1"
sympy = "^1.13.3"
yfinance = "^0.2.51"

[tool.poetry.group.dev.dependencies]
basedpyright = "^1.15.2"
hapless = "^0.7.0"
ipython = "^8.31.0"
jupyter = "^1.0.0"
poethepoet = "^0.31.1"
pre-commit = "^4.0.1"
pyright = "^1.1.374"
ruff = "^0.8.4"

[tool.ruff]
include = ["scripts/*.py", "scripts/*.ipynb"]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D211",
    "COM819",
    "ISC001",
    "D213",
    "D203",
    "FA102",
]

[tool.ruff.format]
docstring-code-format = true


[tool.poe.tasks]

_report_host = "echo 'http://localhost:3333/'"
_hap_preview = "hap run quarto preview ./index.qmd --port 3333 --quiet"
preview = ["_report_host", "_hap_preview"]
