infer-with-first-use = false
preset               = "strict"
project-excludes     = [ "**/_not_posted", "**/_site", "**/_freeze", "**/.*" ]
project-includes     = [ "assets/python", "assets/logo" ]
python-version       = "3.13.0"
