project-includes = [
    "assets/python",
    "assets/logo",
]
project-excludes = [
    "**/_not_posted",
    "**/_site",
    "**/_freeze",
    "**/.*",
]
python-version = "3.13.0"
infer-with-first-use = false
preset = "strict"
