---
format:
  html:
    page-layout: article
title: "Równania Różniczkowe 1"

toc: true
toc-depth: 3
toc-expand: true

---

::: {.course-info-card}

::: {.course-info-grid}

::: {.course-info-item}

::: {.label}

Instytucja

:::

::: {.value}

Uniwersytet Wrocławski

:::

:::

::: {.course-info-item}

::: {.label}

Semestr

:::

::: {.value}

Letni 2017/18

:::

:::

::: {.course-info-item}

::: {.label}

Wykładowca

:::

::: {.value}

dr hab. Andrzej Raczyński

:::

:::

:::

:::

## Informacje O Kursie

- [Zasady zaliczania](../../assets/pdf/RR18-zal.pdf) - Szczegółowe zasady uzyskania
  zaliczenia z kursu.

## Materiały Do Nauki

- [Skrypt Raczyńskiego](<../../assets/pdf/RR 1A - Raczyński.pdf>) - Podstawowy skrypt
  do kursu.
- [Skrypt Palczewskiego](<../../assets/pdf/RRZ skrypt - Palczewski.pdf>) - Obszerny
  skrypt do równań różniczkowych zwyczajnych.
- [Zadania Palczewskiego](<../../assets/pdf/RRZ zadania - Palczewski.pdf>) - Zbiór zadań
  z rozwiązaniami i wskazówkami.

### Równania Różniczkowe Cząstkowe

- [Metoda charakterystyk](../../assets/pdf/charakterystyki.pdf) - Rozwiązywanie równań
  liniowych pierwszego rzędu.
- [Metoda rozdzielania zmiennych](../../assets/pdf/rozdzielaniezmiennych.pdf) - Metoda
  Fouriera dla równań ewolucyjnych.
- [Równanie fali](../../assets/pdf/fala.pdf) - Klasyczne zagadnienia dla równania
  hiperbolicznego.

## Listy Zadań

- [Lista 1](../../assets/pdf/RR18-01.pdf) - Wstęp i podstawowe pojęcia.
- [Lista 2](../../assets/pdf/RR18-02.pdf) - Równania o zmiennych rozdzielonych.
- [Lista 3](../../assets/pdf/RR18-03.pdf) - Równania liniowe 1 rzędu.
- [Lista 4](../../assets/pdf/RR18-04.pdf) - Układy równań liniowych.
- [Lista 5](../../assets/pdf/RR18-05.pdf) - Równania wyższych rzędów.
- [Lista 6](../../assets/pdf/RR18-06.pdf) - Równania cząstkowe.
