---
title: "Równania Różniczkowe 1R"

toc: true
toc-depth: 3
toc-expand: true

format:
  html:
    page-layout: article
---

::: {.course-info-card}
::: {.course-info-grid}
::: {.course-info-item}
::: {.label}
Instytucja
:::
::: {.value}
Uniwersytet Wrocławski
:::
:::

::: {.course-info-item}
::: {.label}
Semestr
:::
::: {.value}
Letni 2017/18
:::
:::

::: {.course-info-item}
::: {.label}
Wykładowca
:::
::: {.value}
prof. Piotr Biler
:::
:::
:::
:::

Program kursu można znaleźć [tutaj](../../assets/pdf/RR1R-prog.pdf).

## Materiały do nauki

* [Skrypt Raczyńskiego](../../assets/pdf/RR 1A - Raczyński.pdf) - Podstawowy skrypt do równań różniczkowych zwyczajnych.
* [Skrypt Palczewskiego](../../assets/pdf/RRZ skrypt - Palczewski.pdf) - Obszerny skrypt do równań różniczkowych zwyczajnych.
* [Zadania Palczewskiego](../../assets/pdf/RRZ zadania - Palczewski.pdf) - Zbiór zadań z rozwiązaniami i wskazówkami.
* [Czynnik całkujący](../../assets/pdf/zupelne.pdf) - Materiały dotyczące równań w postaci różniczki zupełnej.
* [Krzywe ortogonalne](../../assets/pdf/ortogonalne.pdf) - Zastosowania geometryczne równań pierwszego rzędu.


### Równania różniczkowe cząstkowe

* [Metoda charakterystyk](../../assets/pdf/charakterystyki.pdf) - Rozwiązywanie równań liniowych pierwszego rzędu.
* [Metoda rozdzielania zmiennych](../../assets/pdf/rozdzielaniezmiennych.pdf) - Metoda Fouriera dla równań ewolucyjnych.
* [Równanie fali](../../assets/pdf/fala.pdf) - Klasyczne zagadnienia dla równania hiperbolicznego.
* [Równanie ciepła](../../assets/pdf/ciepło.pdf) - Własności i rozwiązania równania parabolicznego.
* [Równanie Laplace'a](../../assets/pdf/laplace.pdf) - Funkcje harmoniczne i zagadnienia brzegowe.


## Listy zadań

* [Lista 00](../../assets/pdf/RR1R-00.pdf) - Powtórzenie z analizy matematycznej.
* [Lista 01](../../assets/pdf/RR1R-01.pdf) - Równania o zmiennych rozdzielonych i liniowe 1 rzędu.
* [Lista 02](../../assets/pdf/RR1R-02.pdf) - Równania zupełne i zastosowania.
* [Lista 03](../../assets/pdf/RR1R-03.pdf) - Istnienie i jednoznaczność rozwiązań (Picard/Peano).
* [Lista 04](../../assets/pdf/RR1R-04.pdf) - Liniowe układy równań (macierzowe).
* [Lista 05](../../assets/pdf/RR1R-05.pdf) - Równania skalarne wyższych rzędów.
* [Lista 06](../../assets/pdf/RR1R-06.pdf) - Stabilność i portrety fazowe.
* [Lista 07](../../assets/pdf/RR1R-07.pdf) - Równania cząstkowe 1 rzędu - metoda charakterystyk.
* [Lista 08](../../assets/pdf/RR1R-08v2.pdf) - Metoda rozdzielania zmiennych.
* [Lista 09](../../assets/pdf/RR1R-09.pdf) - Równania fali, ciepła i Laplace'a.
* [Lista 10](../../assets/pdf/RR1R-10.pdf) - Transformata Laplace'a (nieobowiązkowa).


## Kolokwia

* [Kolokwium 1 (16.04)](../../assets/pdf/RR1R-K1.pdf) - Rozwiązania zadań z pierwszego kolokwium.
* [Kolokwium 2 (11.06)](../../assets/pdf/RR1R-K2.pdf) - Rozwiązania zadań z drugiego kolokwium.
