---
title: "Logowanie"

about:
  template: marquee

execute:
  freeze: true  # never re-render during project render
---

Używamy tej
[recepty](https://docs.python.org/3/howto/logging-cookbook.html#multiple-handlers-and-formatters) wzbogaconej o pakiet [`rich`](https://rich.readthedocs.io/en/stable/introduction.html) do ustawienia logowania w projekcie.
Dostajemy wtedy kolorowe logi na poziomie `INFO` i wyżej w terminalu, a dodatkowe informacje na poziomie `DEBUG` w pliku `log.txt`.

```{python}
import logging
from rich.logging import RichHandler

logger = logging.getLogger("simple_example")
logger.setLevel(logging.DEBUG)

if not logger.hasHandlers(): # <1>
    fh = logging.FileHandler("simple_example.log") # <2>
    fh.setLevel(logging.DEBUG)
    formatter = logging.Formatter( # <3>
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )
    fh.setFormatter(formatter) # <4>
    logger.addHandler(fh) # <5>

    ch = RichHandler() # <6>
    ch.setLevel(logging.INFO)
    logger.addHandler(ch)

logger.debug("debug message") # <7>
logger.info("info message")
logger.warning("warn message")
logger.error("error message")
```

1. logger jest tworzony tylko raz, więc nie dodajemy handlerów więcej niż raz
1. zapisujemy logi DEBUG i wyżej do pliku
1. ustalamy format logów
1. dodajemy formatter do handlera
1. dodajemy handler do loggera
1. wypisujemy logi INFO i wyżej do terminala, używamy RichHandler do kolorowych czytelnych logów
1. przykładowe logi

W pliku dostajemy logi w formacie:

```
2025-05-03 14:36:52,989 - simple_example - DEBUG - debug message
2025-05-03 14:36:52,989 - simple_example - INFO - info message
2025-05-03 14:36:52,991 - simple_example - WARNING - warn message
2025-05-03 14:36:52,992 - simple_example - ERROR - error message
```

## Zadanie

Wybierz jedną z dotychczasowych list zadań i dodaj do niej logowanie.

1. Zamien `print` na `logger.info` lub `logger.debug` w odpowiednich miejscach.
1. Dodaj logowanie błędów w miejscach, gdzie wcześniej był `print` z błędem.
1. Dodaj dodatkowe logi `DEBUG` w miejscach, które sprawiły Ci trudność lub były niejasne.
