---
title: "Równania Różniczkowe 1A (UWr Lato 2017)"

toc: true
toc-depth: 3
toc-expand: true

about:
  template: marquee
---

Prowadzę jedną z grup ćwiczeniowych do wykładu Roberta Stańczego.

## Skrypty

### Równania Różniczkowe Zwyczajne

* Raczyński, A. [Skrypt do kursu](../../assets/pdf/RR 1A - Raczyński.pdf)
* Palczewski, A. [Skrypt do zajęć na UW](../../assets/pdf/RRZ skrypt - Palczewski.pdf)
* Palczewski, A. [Zbiór zadań](../../assets/pdf/RRZ zadania - Palczewski.pdf)

### Równania Różniczkowe Cząstkowe

* [Rozwiązane zadania na metodę charakterystyk](../../assets/pdf/charakterystyki.pdf)
* Karpiński, W.: [Rozwiązane zadania z równań drugiego rzędu](http://www.math.uni.lodz.pl/~karpinw/zadania/RRCz1/II_rzad_zadania.PDF)
* [Rozwiązane zadania na metodę rozdzielania zmiennych](../../assets/pdf/rozdzielaniezmiennych.pdf)

### Listy Zadań
* [Lista 1](../../assets/pdf/RR01.pdf)
* [Lista 2](../../assets/pdf/RR02.pdf)
* [Lista 3](../../assets/pdf/RR03.pdf)
* [Lista 4](../../assets/pdf/RR04.pdf)
* [Lista 5](../../assets/pdf/RR05.pdf)
* [Lista 6](../../assets/pdf/RR06.pdf)
* [Lista 7](../../assets/pdf/RR07.pdf)
* [Lista 8](../../assets/pdf/RR08.pdf)
* [Lista 9](../../assets/pdf/RR09.pdf)
* [Lista 10](../../assets/pdf/RR10.pdf)
* [Lista 11](../../assets/pdf/RR11.pdf)
* [Lista 12](../../assets/pdf/RR12.pdf)
* [Lista 13](../../assets/pdf/RR13.pdf)
* [Lista 14](../../assets/pdf/RR14.pdf)
* [Lista 15 - powtórzeniowa](../../assets/pdf/RR15.pdf)
