---
title: "Równania Różniczkowe 1R (UWr Lato 2018)"

toc: true
toc-depth: 3
toc-expand: true

about:
  template: marquee
---

Prowadzę ćwiczenia do wykładu Piotra Bilera. Program kursu można znaleźć [tutaj](../pdf/RR1R-prog.pdf).

## Materiały do nauki

### Równania różniczkowe zwyczajne

* [Skrypt Raczyńskiego](../pdf/RR 1A - Raczyński.pdf)
* [Skrypt Palczewskiego](../pdf/RRZ skrypt - Palczewski.pdf)
* [Zadania Palczewskiego](../pdf/RRZ zadania - Palczewski.pdf)
* [Czynnik całkujący](../pdf/zupelne.pdf)
* [Krzywe ortogonalne](../pdf/ortogonalne.pdf)

### Równania różniczkowych cząstkowych

* [Metoda charakterystyk](../pdf/charakterystyki.pdf)
* [Metoda rozdzielania zmiennych](../pdf/rozdzielaniezmiennych.pdf)
* [Równanie fali](../pdf/fala.pdf)
* [Równanie ciepła](../pdf/ciepło.pdf)
* [Równanie Laplace'a](../pdf/laplace.pdf)

## Listy zadań

* [Lista 00](../pdf/RR1R-00.pdf) - lista uzupełniająca/powtórzeniowa dotycząca zagadnień z analizy.
* [Lista 01](../pdf/RR1R-01.pdf) - lista z równań liniowych pierwszego rzędu i równań o zmiennych rozdzielonych.
* [Lista 02](../pdf/RR1R-02.pdf) - lista z równań w postaci różniczki zupełnej i zastosowań równań pierwszego rzędu.
* [Lista 03](../pdf/RR1R-03.pdf) - lista z twierdzeń o istnieniu i jednoznaczności.
* [Lista 04](../pdf/RR1R-04.pdf) - lista z liniowych układów równań.
* [Lista 05](../pdf/RR1R-05.pdf) - lista z równań skalarnych wyższych rzędów.
* [Lista 06](../pdf/RR1R-06.pdf) - lista ze stabilności i portretów fazowych.
* [Lista 07](../pdf/RR1R-07.pdf) - lista z metody charakterystyk.
* [Lista 08](../pdf/RR1R-08v2.pdf) - lista z metody rozdzielania zmiennych
* [Lista 09](../pdf/RR1R-09.pdf) - lista z własności równania fali, równania ciepła i równania Laplace'a.
* [Lista 10](../pdf/RR1R-10.pdf) - lista nieobowiązkow z transformaty Laplace'a.


## Kolokwia

* **Kolokwium 1 (16.04):**
  * [Rozwiązania](../pdf/RR1R-K1.pdf)
* **Kolokwium 2 (11.06):**
  * [Rozwiązania](../pdf/RR1R-K2.pdf)
