---
title: "Równania Różniczkowe 1 (UWr Lato 2018)"

toc: true
toc-depth: 3
toc-expand: true

about:
  template: marquee
---

Prowadzę jedną z grup ćwiczeniowych do wykładu Andrzeja Raczyńskiego.

Zasady zaliczania kursu dostępne są na serwisie Moodle oraz [tutaj](../../assets/pdf/RR18-zal.pdf).

## Materiały do nauki równań różniczkowych zwyczajnych:

* **Skrypt do kursu:** Napisany przez Andrzeja Raczyńskiego. [RR 1A - Raczyński](../../assets/pdf/RR 1A - Raczyński.pdf)
* **Skrypt do zajęć na UW:** Napisany przez Andrzeja Palczewskiego. [RRZ skrypt - Palczewski](../../assets/pdf/RRZ skrypt - Palczewski.pdf)
* **Zbiór zadań:** Dostosowany do skryptu AP. [RRZ zadania - Palczewski](../../assets/pdf/RRZ zadania - Palczewski.pdf)

## Materiały do nauki równań różniczkowych cząstkowych:

* **Metoda charakterystyk:** [charakterystyki](../../assets/pdf/charakterystyki.pdf)
* **Metoda rozdzielania zmiennych:** [rozdzielaniezmiennych](../../assets/pdf/rozdzielaniezmiennych.pdf)
* **Równanie fali:** [fala](../../assets/pdf/fala.pdf)

### Listy zadań:

* [Lista 1](../../assets/pdf/RR18-01.pdf)
* [Lista 2](../../assets/pdf/RR18-02.pdf)
* [Lista 3](../../assets/pdf/RR18-03.pdf)
* [Lista 4](../../assets/pdf/RR18-04.pdf)
* [Lista 5](../../assets/pdf/RR18-05.pdf)
* [Lista 6](../../assets/pdf/RR18-06.pdf)

Listy zadań dostępne są również na serwisie Moodle.
